// __RESUME.md/_whatisit/canvas-ui-main/canvas-ui-main/src/lib/GlassObject/GlassObject.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    createGlassObject,
    type GlassObjectInstance,
    type GlassObjectOptions,
  } from "./GlassObjectVanilla";

  interface Props extends GlassObjectOptions {
    class?: string;
  }

  let { class: className = "", ...options }: Props = $props();

  let canvasEl = $state<HTMLCanvasElement>()!;
  let instance: GlassObjectInstance | null = null;

  onMount(() => {
    instance = createGlassObject({ canvas: canvasEl }, options);
    return () => {
      instance?.destroy();
      instance = null;
    };
  });

  $effect(() => {
    instance?.setOptions({ ...options });
  });
</script>

<div class={className} style="position: relative;">
  <canvas
    bind:this={canvasEl}
    style="position: absolute; inset: 0; width: 100%; height: 100%; display: block; touch-action: none;"
  ></canvas>
</div>

// __RESUME.md/_whatisit/canvas-ui-main/canvas-ui-main/src/lib/GlassObject/GlassObject.solid.tsx
/** @jsxImportSource solid-js */

import {
  createEffect,
  onCleanup,
  onMount,
  splitProps,
  type JSX,
} from "solid-js";

import {
  createGlassObject,
  type GlassObjectInstance,
  type GlassObjectOptions,
} from "./GlassObjectVanilla";

export interface GlassObjectProps extends GlassObjectOptions {
  class?: string;
  style?: JSX.CSSProperties;
}

export function GlassObject(props: GlassObjectProps) {
  const [local, options] = splitProps(props, ["class", "style"]);
  let canvasEl!: HTMLCanvasElement;
  let instance: GlassObjectInstance | null = null;

  onMount(() => {
    instance = createGlassObject({ canvas: canvasEl }, { ...options });
  });

  onCleanup(() => {
    instance?.destroy();
    instance = null;
  });

  createEffect(() => {
    instance?.setOptions({ ...options });
  });

  return (
    <div class={local.class} style={{ position: "relative", ...local.style }}>
      <canvas
        ref={canvasEl}
        style={{
          position: "absolute",
          inset: "0",
          width: "100%",
          height: "100%",
          display: "block",
          "touch-action": "none",
        }}
      />
    </div>
  );
}

export type { GlassObjectInstance, GlassObjectOptions };

export default GlassObject;
