// __RESUME.md/_whatisit/canvas-ui-main/canvas-ui-main/src/lib/DitheredObject/DitheredObject.preact.tsx
/** @jsxImportSource preact */

import { useEffect, useRef, useState } from "preact/hooks";
import type { JSX } from "preact";

import {
  createDitheredObject,
  type DitheredObjectInstance,
  type DitheredObjectOptions,
} from "./DitheredObjectVanilla";

export interface DitheredObjectProps extends DitheredObjectOptions {
  className?: string;
  style?: JSX.CSSProperties;
}

export function DitheredObject({
  className,
  style,
  ...options
}: DitheredObjectProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<DitheredObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createDitheredObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { DitheredObjectInstance, DitheredObjectOptions };

export default DitheredObject;

// __RESUME.md/_whatisit/canvas-ui-main/canvas-ui-main/src/lib/DitheredObject/DitheredObject.solid.tsx
/** @jsxImportSource solid-js */

import {
  createEffect,
  onCleanup,
  onMount,
  splitProps,
  type JSX,
} from "solid-js";

import {
  createDitheredObject,
  type DitheredObjectInstance,
  type DitheredObjectOptions,
} from "./DitheredObjectVanilla";

export interface DitheredObjectProps extends DitheredObjectOptions {
  class?: string;
  style?: JSX.CSSProperties;
}

export function DitheredObject(props: DitheredObjectProps) {
  const [local, options] = splitProps(props, ["class", "style"]);
  let canvasEl!: HTMLCanvasElement;
  let instance: DitheredObjectInstance | null = null;

  onMount(() => {
    instance = createDitheredObject({ canvas: canvasEl }, { ...options });
  });

  onCleanup(() => {
    instance?.destroy();
    instance = null;
  });

  createEffect(() => {
    instance?.setOptions({ ...options });
  });

  return (
    <div class={local.class} style={{ position: "relative", ...local.style }}>
      <canvas
        ref={canvasEl}
        style={{
          position: "absolute",
          inset: "0",
          width: "100%",
          height: "100%",
          display: "block",
          "touch-action": "none",
        }}
      />
    </div>
  );
}

export type { DitheredObjectInstance, DitheredObjectOptions };

export default DitheredObject;
