// __RESUME.md/_whatisit/canvas-ui-main/canvas-ui-main/src/lib/ParticleObject/ParticleObject.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

import {
  createParticleObject,
  type ParticleObjectInstance,
  type ParticleObjectOptions,
} from "./ParticleObjectVanilla";

const props = defineProps<ParticleObjectOptions>();

const canvasEl = ref<HTMLCanvasElement | null>(null);

let instance: ParticleObjectInstance | null = null;

onMounted(() => {
  if (canvasEl.value) {
    instance = createParticleObject({ canvas: canvasEl.value }, props);
  }
});

onBeforeUnmount(() => {
  instance?.destroy();
  instance = null;
});

watch(
  () => ({ ...props }),
  (next) => instance?.setOptions(next),
  { deep: true },
);
</script>

<template>
  <div style="position: relative">
    <canvas
      ref="canvasEl"
      style="
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        display: block;
        touch-action: none;
      "
    />
  </div>
</template>

// __RESUME.md/_whatisit/canvas-ui-main/canvas-ui-main/src/lib/ParticleObject/ParticleObject.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    createParticleObject,
    type ParticleObjectInstance,
    type ParticleObjectOptions,
  } from "./ParticleObjectVanilla";

  interface Props extends ParticleObjectOptions {
    class?: string;
  }

  let { class: className = "", ...options }: Props = $props();

  let canvasEl = $state<HTMLCanvasElement>()!;
  let instance: ParticleObjectInstance | null = null;

  onMount(() => {
    instance = createParticleObject({ canvas: canvasEl }, options);
    return () => {
      instance?.destroy();
      instance = null;
    };
  });

  $effect(() => {
    instance?.setOptions({ ...options });
  });
</script>

<div class={className} style="position: relative;">
  <canvas
    bind:this={canvasEl}
    style="position: absolute; inset: 0; width: 100%; height: 100%; display: block; touch-action: none;"
  ></canvas>
</div>
